cartcom/urls.py
#-*- coding:utf-8 -*-
from django.urls import path, include
from django.conf import settings
from django.views.generic.list import ListView
from cartcom import views as v_cartcom
from cartcom import api_view as api_cartcom

urlpatterns = [
    # CART
    path('', v_cartcom.home, name='home'),
    path('<slug:action>/<int:product_id>/', v_cartcom.ListItemCartView.as_view(), name='list_item_incart'),
    path('ajax/detail/<slug:action>/<int:pk>', v_cartcom.home, name='cart_select_article_ligneda'),
    ##
    path('home/<slug:action>/', v_cartcom.ListItemCartView.as_view(), name='product_list'),
    path('product/detail/<int:pk>/', v_cartcom.ListItemCartView.as_view(), name='product_detail'),
    path('addcart/<slug:action>/<int:product_id>/', v_cartcom.ListItemCartView.as_view(), name='add_product_tocart'),
    
    # API
    path('api/product/', api_cartcom.ProductApiList.as_view(), name='api_list_product'),
    
]

cartcompro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('simu/', include('simulator.urls')),
    path('cart/', include('cartcom.urls')),
    path('markdownx/', include('markdownx.urls')), # MarkdownX URL patterns
    # invoices
    path("", include("invoices.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("favicon.png", RedirectView.as_view(url=static("img/favicon.png"))),
]

# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),

    

cartcom/forms.py
# -*- coding:UTF-8 -*-
import re
import datetime
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.forms.utils import ErrorList, ValidationError, ErrorDict
# translate
from django.utils.translation import gettext as _
from django.forms.models import inlineformset_factory
from cartcom import models as cart_models

DURATION_WIDGET_OPTIONS = {
    'format': 'hh:ii',
    'minuteStep': 15,
}
#--------------------------
w_titre = forms.TextInput(attrs={'size': 100, 'class': 'form-control'})
w_slug = forms.TextInput(attrs={'size': 50,  'class': 'form-control'})
text_widget = forms.TextInput(attrs={'size': 40, 'class': 'form-control'})
contenu_widget = forms.Textarea(
    attrs={'cols': 80, 'rows': 12, 'class': 'form-control'})
w_radio_select = forms.RadioSelect(attrs={'class': 'radio'})


semaine_aujourdhui = datetime.datetime.isocalendar(datetime.datetime.now())[1]
SEMAINES_CHOICE = [(sem, sem) for sem in range(semaine_aujourdhui, 53, 1)]
# -- formulaire de recherche Medecin
query_machines = cart_models.ItemArticle.objects.all()
JOURS_SEMAINE = [(1, 'lundi'), (2, 'mardi', ), (3, 'mercredi'),
                 (4, 'jeudi'),  (5, 'vendredi'), (7, 'samedi')]


#---------------------------------
# validation de champ telephone
#---------------------------------
def format_validator(value):
    if not re.match("([a-z]+[ ]*[,][ ]*)+([a-z]+[ ]*)$", value):
        raise ValidationError(u'mauvais format saisie !!')

def format_validator_semaine(value):
    if not re.match("([\d]{2})$", value):
        raise ValidationError(u'mauvais samine saisie !!')



# contruction list
queryset = cart_models.ItemArticle.objects.none(),
query_machine = cart_models.ItemArticle.objects.all()

class SearchMachineForm(forms.Form):
    # cle_recherche = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'size':30}))
    choices=JOURS_SEMAINE
    ###

   

# ------------------------------------
# -- formulaire de recherche Medecin
# ------------------------------------


class SearchDacForm(forms.Form):

    cle_recherche = forms.CharField(max_length=50,
                widget=forms.TextInput(attrs={'size': 60}))

    semaines = forms.CharField(widget=forms.Select(
        choices=SEMAINES_CHOICE), initial='16')

    def __init__(self, *args, **kwargs):
        # appel a la class mère
        super(SearchDacForm, self).__init__(*args, **kwargs)
        # charger les parametre semaine et annee
        # set the user_id as an attribute of the form

        # charger la class bootstrap
        for key, field in self.fields.items():
            if field:
                field.widget.attrs['class'] = 'form-control'
                if field.label:
                    field.label = ugettext(field.label)  # traduire le label
                # les input

                if type(field.widget) in (forms.Select, forms.TextInput,
                                          forms.SelectMultiple,
                                          forms.DateInput):
                    field.widget.attrs['class'] = 'input-lg'
                    # charger place holder
                    field.widget.attrs['placeholder'] = field.label

    class Meta:
        ordering = ('-created',)


class CommentDaForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows':10, 'cols':80}), label='Commentaire' )

    def __init__(self,  *args, **kwargs):
        # appel a la class mère
        super(CommentDaForm, self).__init__(*args, **kwargs)
        initial_arguments = kwargs.get('initial', None)
        updated_initial = {}
        if initial_arguments:
            # We have initial arguments, fetch 'user' placeholder variable if any
            user = initial_arguments.get('user',None)
            # Now update the form's initial values if user  getattr(user, 'email', None)
            updated_initial['comment'] = "toto  ...."

        # set the cac_id as an attribute of the form
        # You can also initialize form fields with hardcoded values
        # or perform complex DB logic here to then perform initialization
        updated_initial['comment'] = 'Please provide a comment'
        # Finally update the kwargs initial reference
        kwargs.update(initial=updated_initial)
        # self.fields['cac_id'].initial = 33


    def save_(self, commit=True):
        # code here

        # 1/ sauvergarde commande DA
        enreg =  super(CommentDaForm, self).save(commit)
        enreg.save()

        # 2/ sauvegarder les commentaire dans entete approv
        entete_da = models.DjangoEnteteAppro.objects.get(cac_id=enreg.pk)
        entete_da.comment = enreg.comment
        entete_da.save()

cartcom/views.py
# -*- coding:UTF-8 -*-
import dateutil.parser
import os
import csv
import random
import logging
import pytz
import json
import io
import base64
import math

import numpy as np
from django_pandas.io import read_frame
import pandas as pd
from . import views as of_views
# from dateutil.parser import *
from django.db import connection
import pandas as pd
from django.db.models import Count
import numpy as np
import datetime
import django
from django.middleware.csrf import get_token
from django.contrib.auth import logout
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core import serializers
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect, reverse
from django.views.generic.edit import UpdateView, CreateView, DeleteView, ModelFormMixin, ProcessFormView, FormView, FormMixin
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateResponseMixin, ContextMixin, View
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.db.models import Q
from urllib.parse import quote
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.http import JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from django.utils.decorators import method_decorator
from cartcom import forms
from cartcom import cart as e_cart
from cartcom import models as cart_models

# Rendez-vous

TIMEZONE = 'Europe/Paris'
# How long ago the timestamp is
# See timedelta doc http://docs.python.org/lib/datetime-timedelta.html
#since = datetime.datetime.utcnow() - date
now = datetime.datetime.utcnow()
now = now.replace(tzinfo=pytz.utc)
tz = pytz.timezone(TIMEZONE)

# Get an instance of a logger
logger = logging.getLogger(__name__)

#Django listview as JSON and Jquery getJSON example

def home(request):
    return HttpResponse("C'est Home ...")
                        
#  la liste des ofs
@method_decorator(login_required, 'dispatch')
class ListOfsView(ListView, FormView, e_cart.Cart):
    template_name = "list_of.html"
    paginate_by = 10  # if pagination is desired
    ## form_class = forms.SearchMachineForm
    object_list = None

    def __init__(self,  **kwargs):
        """
        contructeur avec Cart
        """
        super(ListOfsView, self).__init__(**kwargs)

    def get_context_data(self,  **kwargs):
        context = super(ListOfsView, self).get_context_data(**kwargs)
        # semaine actuelle
        semaine_aujourdhui = datetime.datetime.isocalendar(datetime.datetime.now())[1]
        img_choice = random.choice(range(10))
        #context['form'] = self.form_class
        form = forms.SearchMachineForm()
        # form.initial.update( {'user': self.request.user, 'cle_recherche': v_semaine})
        return context

    def get_form_kwargs__(self):
        """This method is what injects forms with their keyword
            arguments."""
        # grab the current set of form #kwargs
        kwargs = super(ListOfsView, self).get_form_kwargs()
        # Update the kwargs with the user_id
        kwargs['user'] = self.request.user
        return kwargs

    def get_queryset(self, **kwargs):
        v_semaine = kwargs.get('semaine')
        v_annee = kwargs.get('annee')
        v_machine = kwargs.get('code_machine')
        messages.add_message(self.request, messages.INFO,
                             '**kwrag**=%s' % v_semaine)

        self.object_list = planif_models.DjangoOf.objects.filter(statut__in=['P', 'D'],
                                                          semaine=v_semaine,
                                                          annee=v_annee)
        #self.object_list = planif_models.DjangoOf.objects.all()
        return self.object_list

    def post__(self, request, *args, **kwargs):
        """
        """
        # 1/ on va recperer les criteres saisie pour selectionner les ofs
        jr_choisies = []
        jours_semaine = ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi']

        form = forms.SearchMachineForm(request.POST)
        #form.is_valid()
        messages.add_message(self.request, messages.INFO, 'je suis dans post kwrag=%s' % request.POST.keys())
        # on verifie si le formulaire est valide
        if request.method == 'POST' and form.is_valid() :
            # 2/ on récupere la semaine, annee, et machine saisie par l'utilsateur
            machine = request.POST["machines"]
            semaine = request.POST["semaines"]
            jours_semaine   = request.POST["jours_semaine"]
            annee = kwargs.get('annee', None)
            #machine = form.cleaned_data["machines"]
            # on recupere les jour de destinations
            #
            for jour in request.POST.getlist('jours_semaine') :
                    jr_choisies.append(jour)

            # 3/ save les elements et on relance la recherche des ofs
            self.object_list = planif_models.DjangoOf.objects.filter(statut__in=['P'],
                                                              semaine=semaine,
                                                              annee=annee,
                                                              machine_travail_id = machine)

            # 4/ test si OF est deja concerné par une Cac
            self.object_list= list(self.object_list)
            for index, of in  enumerate(self.object_list):
                if not models.DjangoLigneCommandeApprov.filter(product_id=of.product_id).exists():
                    messages.add_message(self.request, messages.INFO, 'Of completed DA=%s' % of.product_id)
                    of.completetd=True



            #return HttpResponse("ok" + '---'.join(jours_semaine))
            #return self.form_invalid(form)
            return render(request, self.template_name, locals())

        else :
            # return
            erreurs = [ field.errors for field in form ]
            return render(request, self.template_name, locals())


    def render_json_response(self, queryset):
        """
        export json format
        """
        json_data = serializers.serialize('json', queryset)
        # Proceed to create your context object containing the columns and the data
        return HttpResponse(json_data, content_type='application/json')

    def api_simulation_demande_approv(self):
        # 0- recuperer les ofs du panier
        propositions = []
        mes_articles_of = self.cartdb.item_set.all()

        new_da_simu = models.DemandeApproSimulee.objects.get(pk=214)

        # 4 afficher la proposition
        all_columns = ['demande_appro', 'product_id', 'article', 'commande',
                       'machine', 'quantite_commandee', 'quantite_produit', 'selected']

        lignes_da = new_da_simu.mes_lignes.all()
        #.values_list( 'demande_appro', 'product_id', 'article', 'commande', 'machine', 'quantite_commandee', 'quantite_produit', 'selected' )
        #lignes_da  = models.LigneDemandeApproSimulee.objects.filter(demande_appro = 110)
        # messages.add_message(self.request, messages.INFO, 'lignes DA = %s' % lignes_da)

        json_data = serializers.serialize('json', lignes_da)
        #return self.render_json_response(lignes_da)

        data_test = {"products":[{"id":1,"quantity":1,"name":"Compass"},
                                 {"id":2,"quantity":0,"name":"Jacket"},
                                 {"id":3,"quantity":5,"name":"Hiking Socks"},
                                 {"id":4,"quantity":2,"name":"Suntan Lotion"}]}

        return json_data

    def get(self, request,   **kwargs):
        # on recupere le contexte
        self.request = request
        data = ""

        # initialisation objet panier
        Cart.__init__(self, request)
        #

        #self.object_list = planif_models.DjangoOf.objects.filter(semaine=v_semaine, annee=v_annee)
        self.get_queryset(**kwargs)
        #messages.add_message(None, messages.INFO, 'init objet cart_id.%s' % kwargs)
        v_semaine = kwargs.get('semaine')
        v_annee = kwargs.get('annee')
        v_machine = kwargs.get('code_machine')

        product_id = kwargs.get('product_id')
        quantitee = abs(float(kwargs.get('quantitee', 0)))

        action = kwargs.get('action')

        if action == "simvuejs":
            context = self.simulation_demande_approv(kwargs)
            return render(self.request, "propos_da_vues.html", locals())

        elif action == "selecteditem":
            item_id = kwargs.get('lda_pk')
            self.ajax_select_article_ligneda(item_id)

        # return si request est de type ajax on return une reponse json sino return response http
        # context = super(ListOfsView, self).get_context_data(**kwargs)
        context = self.get_context_data(**kwargs)

        if request.is_ajax():
            return JsonResponse(data, status=200, safe=False)
        else:
            return self.render_to_response(context)

    # ---------------
    # -- return to sender
    # ---------------
    def return_to_sender(self):
        return HttpResponseRedirect(reverse('list_of_view', kwargs={'semaine': 38, 'annee': 18}))

    # --------------------------
    # --ajax cart validate DA
    # ---------------------------
    def ajax_cart_validate_da(self, da_pk):
        """
        Update ligne DA SELECTED
        """
        resp = {}
        try:
            models.DemandeApproSimulee.objects.filter(pk=da_pk).update(statut=3)
            resp['status'] = "OK pk = %s  " % (da_pk)
            return da_pk

        except Exception as err:
            resp['status'] = "KO pk=%s  " % (self.request.GET.get('lda_pk', 0))

        return json.dumps(resp)

    # -------------------------------
    # --ajax select article ligneda

cartcom/templates/da/cac_template.html
<!-- template for the modal component -->
<template class="container" id="cac_template">
	<table class="table table-striped" >
				<tr class="text-center" :key=elem.id  v-show="!active" >
					<td> <input type="checkbox" v-bind:checked="checked" v-on:change="$emit('checker', $event.target.checked)" class="form-check-input" />
					</td>
					<td> [[ elem.pk ]] </td>
					<td> [[ elem.demande_appro_id ]] </td>
					<td> [[ elem.created | formatDate ]] </td>
					<td> [[ elem.created_by ]] </td>
					<td> [[ elem.entrepot  ]] </td>
					<td> [[ elem.zone_appro]] </td>
					<td> [[ elem.semaine  ]] </td>
					<td> [[ elem.annee  ]]  </td>
					<td>
						 <button  v-show="false"  title="Ajouter un commentaire" id='bt_12345' type='button'  class="btn btn-lg btn-warning" data-toggle='modal'
							data-target='#ModalFormMessage'> <span class='fa fa-plus'></span>[[elem.pk]]</button>
					</td>

					<td v-show="false"> <A @click="form_active=!form_active" title="Ajouter un commentaire" class="btn btn-lg btn-info" >
						<em class="fa fa-plus"> </em></A>
						<form id="formComment"  action="#" @submit.prevent="checkComment(elem.pk), form_active=!form_active"   v-show="!form_active">
							{% csrf_token %}
							<!-- <input type="hidden"  id="cle_csrf" v-model="csrf_token"  />     -->
							<textarea name="comment" v-model="comment" placeholder="saisir ici un commentaire" rows="8" cols="80"> </textarea>
							<input class="btn btn-success" type="submit"   value="sauvegarder" />
						</form>
					</td>


					<td> <A  :href="url_update_da" title="Modifier l'entete de la demande appro ..." class="btn btn-lg btn-warning" target="_blank" /><em class="fa fa-plus"></em></A> </td>
					<td> <A  :href="url_show"  data-toggle="tooltip"  title=" Voir Détails" class="btn btn-lg btn-warning" ><em class="fa fa-eye"></em></A> </td>
					<td> <A  :href="url_print" data-toggle="tooltip"  title="imprimer" class="btn btn-lg btn-warning"  target="_blank"><em class="fa fa-print"></em></A> </td>
					<td> <A  :href="url_export" data-toggle="tooltip"  title="Exporter en fichier excel"  class="btn btn-lg btn-warning" target="_blank"><em class="fa fa-file"></em></A> </td>
					<td> <A v-show="true" :href="url_delete_da" data-toggle="tooltip" @click.prevent="emit_open_modal_confirm(elem.pk)" title="Suppression Demande approvisionnement"
            	v-bind:class="{
                'btn btn-lg btn-warning' : elem.created_by!=1,
								'btn btn-lg btn-info  btn-block' : elem.created_by==1,}" >
              <em  class="fa fa-trash"></em></A></td>

					<td>
					</td>


				<!-- template for the modal component -->
			  {% include 'modal_template.html' %}
				</tr>
	</table>
</template>

cartcom/templates/da/cart.html
{% extends 'base_of.html' %}
{% load i18n static %}

{% block left_side %}
  <h4><img class="pull-left " src="{% static 'images/chariot.jpeg' %}" height="40" width="40" />
    Panier Demande approvisionnment</h4>
    <hr>
    {% include 'da_left_menu.html' %}
  {% endblock left_side %}

  {% block right_side %}
  {% endblock %}


  {% block main_side %}

<div class="container-fluid" >
  <div class="jumbotron">
  	<h2 class="text-center"> Gestion OFs  </h2>
  	<h4 class="text-center text-primary"> Année  2018</h4>
  </div>

  <div class="container" id="app">
    <table   class="table table-bordered table-striped">

    	<thead>
        <tr class="font-weight-bold text-center" >
        	<th>Check</th>
          <th><a @click="sort('date_debut_reelle')">Date debut</a></th>
          <th><a @click="sort('code_of')">Code of</a> </th>
          <th><a @click="sort('statut')">Statut</a>  </th>
          <th><a @click="sort('commande_id')">Commande</a></th>
        	<th><a @click="sort('client_id')">Client</a> </th>
          <th><a @click="sort('quantite_prevue')"> Quantite</a></th>
          <th colspan="4"> Action</th>
        </tr>
    	</thead>
      <table>
        <tbody >
          <compof v-for="article in sortedCats"  :key="article.id" v-bind:of="article"> </compof>
        </tbody>
      </table>
[[ sortedCats ]]
    </table>

    <div class="row" >
    <button class='btn-warning btn-lg  ' @click="prevPage">Précedent</button>
    <button class='btn-warning btn-lg  ' @click="nextPage">Suivant</button>
    </div>

  </div>

  <template class="container" id="of_template">
      <table   class="table table-bordered table-striped">
  				<tr class="text-center" :key=of.id  v-show="active" >
  					<td> <input type="checkbox"
  							v-bind:checked="checked"
  					    v-on:change="$emit('checker', $event.target.checked)"
  					 class="form-check-input" />
           </td>

            <td> [[ of.date_debut_reelle  ]]</td>
            <td> [[ of.code_of  ]]</td>
  					<td> [[ of.statut ]]</td>
  					<td> [[ of.commande]]</td>
  					<td> [[ of.client  ]]</td>
  					<td> [[ of.quantite_prevue ]]</td>
            <td colspan="4">
    					 <A href="#" @click.prevent="of.statut='P'"  href="" class="" > <i class="fa fa-pencil" style="font-size:14px;">Planifier </i>  </A>
    				   <A href="#" @click.prevent="of.statut='L'" href="" class="" > <i class="fa fa-pencil" style="font-size:14px;">Lancer </i>  </A>
    					 <A href="#" @click.prevent="of.statut='S'"  href="" class="" > <i class="fa fa-pencil" style="font-size:14px;">Cloturer </i>  </A>
            </td>
            <td>
  						<A href="#" class="btn"
  						v-bind:class="{
  								'btn-success btn-md btn-block' : 	of.statut == 'S',
  								'btn-info btn-md btn-block' : 		of.statut == 'P',
  								'btn-danger btn-md btn-block' : 	of.statut == 'L',
  							  'btn-warning btn-md btn-block' : 	of.statut == 'C',}" >
  							<span v-if="of.statut == 'L'" > Lancer </span>
  							<span v-if="of.statut == 'C'"> Creer </span>
  							<span v-if="of.statut == 'P'"> planifier </span>
  							<span v-if="of.statut == 'S'" > Cloturer </span>
  						</A>
  					</td>
  				</tr>
        </table>
  </template>

  <!-- VUEJS  -->
	<script src="{% static 'vuejs/vue2.3.4.js' %}"></script>
	<script src="{% static 'vuejs/app_2.js' %}"></script>
	<!-- VUEJS  -->
  {% endblock %}
</div>

cartcom/templates/da/da_left_menu.html
<ul class="list-group">
  <li class="list-group-item text-info"> <h4> <a href="{% url 'home' %}" >  Accueil </a></h4></li>
  <li class="list-group-item text-info"> <h4> <a href="{  'list_item_incart' 'listitem' }" >  Panier </a></h4></li>
  <li class="list-group-item text-info"> <h4> <a href="{ 'da_list_cac' 'list'  }" >Mes demandes DA </a></h4></li>
  <li class="list-group-item"> <h4> <a href="{ 'das_details_product'  }">  Dernière propositon DA Simulée  </a></h4></li>
</ul>

cartcom/templates/da/da_right_menu.html
<ul class="list-group">
  <li class="list-group-item"> <a class="nav-link" href="{% url 'fullcalendar_semaine' 'of_calendar' semaine annee  7 %}">Ofs encours</a> </li>
  <li class="list-group-item"> <a class="nav-link" href="{% url 'fullcalendar_semaine' 'of_calendar' semaine annee  8 %}">Ofs en retard</a> </li>
  <li class="list-group-item"> <a class="nav-link" href="{% url 'fullcalendar_semaine' 'of_calendar' semaine annee  9 %}">Ofs planifiés</a> </li>
</ul>

cartcom/templates/da/modal_template.html
<!-- template for the modal component -->
<script type="text/x-template" id="modal-cac-template">
  <transition name="modal">
    <div class="modal-mask">
      <div class="modal-wrapper">
        <div class="modal-container">

          <div class="modal-header">
            <slot name="header">
              Confirmation
            </slot>
          </div>

          <div class="modal-body">
            <slot name="body">
              Souhaitez-vous supprimer la Demande d'approvisionnment ?
            </slot>
          </div>
          <div class="modal-footer">
            <slot name="footer">
              <button class="modal-default-button" data-dismiss='modal' @click="$emit('close');"> Quitter </button>
              <button id="id_validation"  class="modal-default-button" @click.prevent="deleteDa([[ elem.pk ]] ); $emit('close');">

                <em class="fa fa-save"></em>Confirmez</button>
            </slot>
          </div>

        </div>
      </div>
    </div>
  </transition>
</script>

cartcom/templates/da/pandas_of.html
{% extends 'base_home.html' %}
{% load i18n static staticfiles %}

{% block body %}

   <table id='datatable'></table>

<!-- Yep, all you need is a properly identified
     but otherwise empty, table tag!
-->
<!-- -->
<script src="{% static 'bower_components/bootstrap-table/dist/bootstrap-table.min.js' %}" ></script>


<!-- jQuery first, then Popper.js, then Bootstrap JS, and then Bootstrap Table JS-->
<!-- <script src="https://unpkg.com/bootstrap-table@1.13.4/dist/bootstrap-table.min.js"></script>-->

<script type="text/javascript">

$(document).ready(function() {

 $('#datatable').bootstrapTable({
    search: true,
    striped: true,
    pagination: true,
    showColumns: true,
    showToggle: true,
    showExport: true,
    sortable: true,
    paginationVAlign: 'both',
    pageSize: 25,
    pageList: [10, 25, 50, 100, 'ALL'],
    //columns: [{   field: 'code_of',    title: 'Item ID'  }, {    field: 'commande',    title: 'Item Name'  }],  // here is where we use the column content from our Django View
    columns : {{ columns|safe }},
    //data: [{"id":1001,"code_of":"C2019021059", "commande":"181407"}]
    data: {{ data|safe }}

  });


  $('#table').bootstrapTable({
  columns: [{
    field: 'id',
    title: 'Item ID'
  }, {
    field: 'name',
    title: 'Item Name'
  }, {
    field: 'price',
    title: 'Item Price'
  }],
  data: [{
    id: 1,
    name: 'Item 1',
    price: '$1'
  }, {
    id: 2,
    name: 'Item 2',
    price: '$2'
  }]

  });

    });
</script>

{% endblock %}

cartcom/templates/da/search_dac.html
<!-- Services Recherche -->
 {% load i18n   %}

	<form action="" method="post" name="sentSearch" id="contactForm" class="form-inline">
			 {% csrf_token %}
			<div class="row">
				<div class="form-group">
					<div class='row'>
						<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
								 <div class="input-group input-group-lg text-large">
											{{ form.semaines.errors }}
											<span class="input-group-addon">
                        <i class="fa fa-calendar"></i></span>
											{{ form.semaines  }}
								 </div>
						</div>


						<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
								 <div class="input-group input-group-lg">
											<span class="input-group-addon bg-warning">
                        <A   href="/of/listof/{{semaine}}/{{annee}}/{{code_machine}}" <i class="fa fa-search"></i> </A></span>
								 </div>
						</div>
							 </div>
				</div>
			</div>
	</form>



<script  type='text/javascript'>
  //$('input').addClass("form-control");
  $('select').addClass("text-select-option");
  $('.errorlist').addClass("list-unstyled text-warning");

  // --------------
  $("#id_semaines").change(function(event) {
    var semaine = $(this).val();
    url = "/of/da/listdac/12345/".replace(/12345/, semaine);

    location.href = url;
    location.replace(url)
    //window.location.reload(false);
  });
</script>